name: snekmer
channels:
  - anaconda
  - bioconda
  - numba
  - conda-forge
dependencies:
  - python >= 3.9
  - biopython
  - defaults::pyarrow
  - jinja2
  - matplotlib
  - numpy == 1.22.3
  - numba >= 0.56
  - scipy
  - pandas
  - seaborn
  - scikit-learn == 1.2.2
  - snakemake == 7.0
  - tabulate == 0.8.10
  - umap-learn
  - hdbscan == 0.8.29
  - pip
  - pip:
      - snekmer
      - -e git+https://github.com/PNNL-Compbio/bsf-jaccard-py#egg=bsf
