name: snekmer
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - matplotlib
  # - numpy >= 1.22.3
  - pandas
  - seaborn
  - scikit-learn
  - snakemake >= 6.0
  - umap-learn
  - hdbscan
