name: snekmer
channels:
  - anaconda
  - bioconda
  - numba
  - conda-forge
dependencies:
  - python >= 3.9
  - biopython
  - pyarrow
  - jinja2
  - matplotlib
  - numpy == 1.22.3
  - numba >= 0.56
  - scipy
  - pandas == 1.4.2
  - seaborn
  - scikit-learn == 1.2.2
  - snakemake == 7.0
  - tabulate == 0.8.10
  - umap-learn
  - hdbscan == 0.8.29  # see: https://stackoverflow.com/questions/76714347/hdbscan-error-typeerror-numpy-float64-object-cannot-be-interpreted-as-an-int
  - pip
  - pip:
      - -e git+https://github.com/PNNL-CompBio/Snekmer#egg=snekmer
