name: snekmer
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - matplotlib
  - numpy >= 1.22.3
  - scipy
  - pandas
  - seaborn
  - scikit-learn
  - snakemake >= 6.0
  - umap-learn
  - hdbscan
  - pip
  - pip:
      - -e git+https://github.com/PNNL-Compbio/bsf-jaccard-py#egg=bsf
