name: snekmer
channels:
  - anaconda
  - bioconda
  - numba
  - conda-forge
dependencies:
  - python >= 3.9
  - biopython
  - matplotlib
  - numpy >= 1.22.3
  - numba >= 0.56
  - scipy
  - pandas
  - seaborn
  - scikit-learn
  - snakemake == 7.0
  - umap-learn
  - hdbscan
  - pip
  - pip:
      - -e git+https://github.com/PNNL-CompBio/Snekmer@v1.0.0#egg=snekmer
      - -e git+https://github.com/PNNL-Compbio/bsf-jaccard-py#egg=bsf
