# required params
k: 14
alphabet: 0  # choices 0-5 or names (see snekmer.alphabet),  or None
min_rep_thresh: 1
processes: 2

# optional params
start: False
end: False
nucleotide: False
randomize_alphabet: False
walk: False
# custom_alphabet: {'custom_alphabet': {}}

input:
  example_index_file: False
  feature_set: False
  file_extensions: ['fasta', 'fna', 'faa', 'fa']
  regex: "[a-z]{3}[A-Z]{1}"  # regex to parse family from filename

output:
  # active params
  nested_dir: False  # if True, saves into {save_dir}/{alphabet name}/{k}
  verbose: True  # if True, logs verbose outputs
  format: 'simple'  # choices: ['simple', 'gist', 'sieve']
  filter_duplicates: True
  n_terminal_file: False
  shuffle_n: False
  shuffle_sequences: False
  # currently inactive
  filename: False  # customize filename
  kmer_output: True

score:
  scaler: True
  scaler_kwargs: {'n': 0.25}
  labels: None
  lname: None  # label name

model:
  n: 100
  cv: 5
  use_score: False
  random_state: None

cluster:
  method: 'correlation'
  params: {'t': 0.75, 'criterion': 'distance', 'metric': 'correlation', 'method': 'weighted'}
