# required params
k: 14
alphabet: 0 # choices 0-5 or names (see alphabet module), or None

# input/output params
input_file_exts: ["fasta", "fna", "faa", "fa"] # specify valid input file extensions
nested_output: False # if True, saves into {save_dir}/{alphabet name}/{k}

# scoring params
score:
  scaler: True
  scaler_kwargs: { "n": 0.25 }
  labels: None
  lname: None # label name

# model params
model:
  n: 100
  cv: 5
  use_score: False
  random_state: None

# cluster params
cluster:
  method: "correlation"
  params:
    {
      "t": 0.75,
      "criterion": "distance",
      "metric": "correlation",
      "method": "weighted",
    }
# optional params
# future params
# custom_alphabet: {'custom_alphabet': {}}
# deprecated params
# processes: 2
# min_rep_thresh: 1
# start: None
# end: None
# nucleotide: False
# randomize_alphabet: False
# walk: False
# input:
# example_index_file: None
# kmer_set_file: None # file containing kmer feature set
# regex: "[a-z]{3}[A-Z]{1}" # regex to parse family from filename
# output:
# verbose: True # if True, logs verbose outputs
# format: "simple" # choices: ['simple', 'gist', 'sieve']
# filter_duplicates: True
# n_terminal_file: None
# shuffle_n: False
# shuffle_sequences: False
# # currently inactive
# filename: False # customize filename
# kmer_output: True
