input:
  # location of all input fasta files
  fasta_dir: "../example"
  example_index_file: False
  feature_set: '../example/model_features.txt'
  file_extensions: ['fasta', 'fna', 'faa', 'fa']

# kmer pipeline parameters
k: 14
start: False
end: False
nucleotide: False
map_function: 'reduced_alphabet_0'  # choices: 0-5
randomize_alphabet: False
min_rep_thresh: 1
walk: False
full_kmer_list: False
processes: 2

output:
  save_dir: "../../output"
  verbose: True
  format: 'simple'  # choices: ['simple', 'gist', 'sieve']
  filename: False
  filter_duplicates: True
  n_terminal_file: False
  shuffle_n: False
  shuffle_sequences: False
  kmer_output: True

score:
  labels: None
  lname: None  # label name

model:
  use_score: False
  n: 100
