# required params
k: 14
alphabet: 0 # choices 0-5 or names (see alphabet module), or None

# input/output params
#input_dir: None # defaults to 'input'
input_file_exts: ["fasta", "fna", "faa", "fa"] # specify valid input file extensions
input_file_regex: ".*" # regex to parse family from filename
nested_output: False # if True, saves into {save_dir}/{alphabet name}/{k}

# scoring params
score:
  scaler: True
  scaler_kwargs: { "n": 0.25 }
  labels: None
  lname: None # label name

# cluster params
cluster:
  method: "agglomerative-jaccard"
  params:
    {
      "n_clusters": None,
      "linkage": "average",
      "distance_threshold": 0.92,
      "compute_full_tree": True,
    }
  cluster_plots: False

  # clustering distance matrix params
  min_rep:
  max_rep:
  save_matrix: True
  dist_thresh: 100

# model params
model:
  cv: 5
  random_state: None

# search params
model_dir: "output/model/"
basis_dir: "output/kmerize/"
score_dir: "output/score/"

# motif params
motif:
  n: 5 
  families: 2
