# required params
k: 14
alphabet: 0 # choices 0-5 or names (see alphabet module), or None

# input/output params
input_dir: None # defaults to 'input'
input_file_exts: ["fasta", "fna", "faa", "fa"] # specify valid input file extensions
input_file_regex: "[a-z]{3}[A-Z]{1}" # regex to parse family from filename
nested_output: False # if True, saves into {save_dir}/{alphabet name}/{k}

# scoring params
score:
  scaler: True
  scaler_kwargs: { "n": 0.25 }
  labels: None
  lname: None # label name

# cluster params
cluster:
  method: "correlation"
  params:
    {
      "t": 0.75,
      "criterion": "distance",
      "metric": "correlation",
      "method": "weighted",
    }
  cluster_plots: True

  # clustering distance matrix params
  min_rep:
  max_rep:
  save_matrix: False
  dist_thresh: 100

# model params
model:
  cv: 5
  random_state: None

# search params
model_dir: "/path/to/output/model/"
basis_dir: "/path/to/output/labels/"
score_dir: "/path/to/output/score/"
