name: CI

# specify trigger events for ci workflow
on:
  push:
    branches: [main, tests]
  pull_request:
    branches: [main, tests]

jobs:
  # step 0: dependencies
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # setup environment
      - name: Create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: anaconda,conda-forge,bioconda,numba
          auto-activate-base: false
          activate-environment: snekmer
          environment-file: .test/test-env.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show
      - shell: bash -l {0}
        run: mamba install -c conda-forge -yn snakemake==7.0

  # step 2: apply formating and linting
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply snakefmt
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: snekmer/rules/
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Lint:
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - uses: actions/checkout@v3
      - name: Lint cluster.smk
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: snekmer/rules/cluster.smk
          args: "--lint"
      - name: Lint model.smk
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: snekmer/rules/model.smk
          args: "--lint"
      - name: Lint search.smk
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: snekmer/rules/search.smk
          args: "--lint"

  # step 3: testing
  Test:
    runs-on: ubuntu-latest
    needs:
      - Format
      - Lint
      - Build

    steps:
      # test clustering step
      - name: Snekmer Cluster
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: snekmer/rules/cluster.smk
          args: "--cores 1 --use-conda --conda-cleanup-pkgs cache --show-failed-logs --conda-frontend mamba"
          stagein: conda config --get channel_priority --json |
            rm -rf .test/output

      # test modeling step
      - name: Snekmer Model
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: snekmer/rules/model.smk
          args: "--cores 1"
          stagein: |
            rm -rf .test/output

    # - name: search
    #   uses: snakemake/snakemake-github-action@v1
    #   with:
    #     snakefile: "snekmer/rules/search.smk"
