name: CI

# specify trigger events for ci workflow
on:
  push:
    branches: [main, tests]
  # pull_request:
  #   branches: [main, tests]

jobs:
  # step 2: apply formating and linting
  # Format:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Apply snakefmt
  #       uses: github/super-linter@v4
  #       env:
  #         VALIDATE_ALL_CODEBASE: false
  #         DEFAULT_BRANCH: main
  #         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         VALIDATE_SNAKEMAKE_SNAKEFMT: true
  # Lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Lint workflow
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .test
  #         snakefile: snekmer/rules/cluster.smk
  #         args: "--lint"

  # step 0: dependencies
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup environment
      - name: create_environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: anaconda,conda-forge,bioconda,numba
          auto-activate-base: false
          activate-environment: snekmer
          environment-file: .test/test-env.yml
      - run: conda info
      - run: conda list
      - run: conda config --show

  # step 3: testing
  Test:
    runs-on: ubuntu-latest
    needs:
      # - Format
      # - Lint
      - Build

    steps:
      # test clustering step
      - name: Snekmer Cluster
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .test
          snakefile: snekmer/rules/cluster.smk
          args: "--cores 1 --use-conda --conda-cleanup-pkgs cache"
          stagein: "rm -rf .test/output" # additional preliminary commands to run (can be multiline)

      # test modeling step
      - name: Snekmer Model
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .test
          snakefile: snekmer/rules/model.smk
          args: "--cores 1"
          stagein: "rm -rf .test/output"

    # - name: search
    #   uses: snakemake/snakemake-github-action@v1
    #   with:
    #     snakefile: "snekmer/rules/search.smk"
